# Generated by Django 3.1.2 on 2020-10-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Absent')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('image', models.ImageField(upload_to='student/')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.classes', verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True)),
                ('attendance', models.PositiveIntegerField()),
                ('absent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.absents', verbose_name='Absents')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.students', verbose_name='Student Name')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.teachers', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='absents',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.classes', verbose_name='Class'),
        ),
    ]
