# Generated by Django 3.1.2 on 2020-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
